---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http
  namespace: stage
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ks.stephenekundayo.xyz
    http:
      paths:
      - path: /NENEFE/.github/scripts
        frontend:
          serviceName: neneapp
          servicePort: 3005




