apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name:  ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name:   client-cluster-ip-service
              port:
                number: 3005
        - path: /api/?(.*)
          pathType: Prefix
          backend:
            service:
              name:   server-cluster-ip-service
              port:
                number: 3000
                
---
kind: Service
apiVersion: v1
metadata:
  name:  Service Name
spec:
  selector:
    app:  Selector Label
  type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080

---
