apiVersion: apps/v1
kind: Deployment
metadata:
  name: neneapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nenewebapp
  template:
    metadata:
      labels:
        app: nenewebapp
    spec:
      containers:
      - name: nenecontainer 
        image: 843625722910.dkr.ecr.us-east-1.amazonaws.com/shopnene@sha256:cdf997ef9ade81483ba99352b57cc287a25d66120159867b8fda480a3f4e2b77
        ports:
        - containerPort: 3005




---
