#workflow for building and deploying to a staging and production server

name: Deploy to staging


on:
  workflow_run:
    workflows: [Deploy Next.js site to Pages]
    types: [completed]

   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering wokflow has failed'

      

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


#install dependencies

      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      
    
  Deploy_to_EC2:
    name: Deploy to server
    runs-on: ubuntu-latest
    environment: staging

    needs: build

    steps:
      - name: Remote ssh actions
        uses: garygrossgarten/github-action-scp@release
        with:
            localpath: './build'
            remotepath: '/home/ubuntu/NeneFe/build/'
            privatekey: ${{ secrets.SSH_PRIVATEKEY  }}
            host: ${{ secrets.SSH_HOST  }}
            username: ${{ secrets.USERNAME  }}
            port: ${{ secrets.PORT }}
            


      
