#workflow for building and deploying to a staging and production server

name: Deploy to staging


on:
  workflow_run:
    workflows: [Deploy Next.js site to Pages]
    types: [completed]

   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering wokflow has failed'

      

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


#install dependencies

      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      
    
  Deploy_to_EC2:
    name: Deploy to server
    runs-on: ubuntu-latest
    environment: staging

    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Remote ssh access
        env:
            SSH_PRIVATEKEY: ${{ secrets.SSH_PRIVATEKEY  }}
            SSH_HOST : ${{ secrets.SSH_HOST  }}
            USERNAME : ${{ secrets.USERNAME  }}
            
        run: |
          echo "$SSH_PRIVATEKEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${SSH_HOST} '
            sudo su
            ls 
            cd /NeneFe &&
            git checkout dev &&
            git fetch --all &&
            git reset --hard origin/dev &&
            git pull origin dev'
